### ISSUE TITLE
A file format standard for specifying jaxley models 

### ISSUE THREAD

**Issue by jnsbck** [jaxleyverse/jaxley#362]
@kyralianaka implemented some kind of `yaml` parser to set up her networks in jaxley. I think this is a really great tool!
Since I am currently  writing an `io` submodule, I thought it would be a great addition to also include a file parser, that would let the user specify networks without having to code. I.e. via `from_yaml`, `to_yaml` or `from_json`, `to_json`. To do this well, we should come up with a file format that is suitable for this, such that we can write a parser. Therefore I am starting this discussion, so you can all chime in.

### Considerations:
- Modules should be specifiable at every level.
- one should be able to name everything (like groups, channels, etc.)
- connectivities should be specifiable
- morphology (could be fpath to .swc file or sth.) 
- Format should be as future proof as possible (I think since the API is pretty much set in stone now, this should be doable if we think careful about it)
- every parameter should be setable ideally.

### Idea sketch:
I think something along the lines of the following could work.
```yaml
Network:
 - name: net
 - Connection:
  - type: TestSynapse
  - from:
   - cell: cell1
   - branch: 0
   - comp: 0
  - to:
   -  cell: cell2
   - branch: 1
   - comp: 1
 - Cell:
  - name: cell1
  - Connection:
   - type: branch
   - from:
    - branch: branch1
   - to:
    - branch: branch2
  - Branch:
   - name: branch1
   - group: soma
   - nsegs: 4
   - compartments: comp1
   - Compartment: 
    - name: comp1
    - Channel:
     - type: HH_Na
     - name: Na1
     - gNa: 0.1
     - eNa: 35
  - Branch:
   - name: branch2
   - nsegs: 4
   - compartments: comp1
   - Compartment: 
    - name: comp1
- Cell:
 - name: cell2
 - ...
```

another idea sketch, that is more similar to how jaxley is set up
```yaml
Compartment:
 - name: comp1
 - ...

Compartment:
 - name: comp2
 - ...


Branch:
 - name: branch1
 - input: 
  - comp1
  - comp1
  - comp1
  - comp1

...

Network:
 - name: net1

```
